#!/bin/sh
set -e
KEEPBRIGHT=${KEEPBRIGHT:-/var/lib/keepbright/brightness}

if [ -f "$KEEBPRIGHT"]; then
    while IFS='' read -r line; do
        IFS=' ' read -r dev brightness <<-_EOF_
        $line
_EOF_
        echo $brightness > "$dev"/brightness
    done < "$KEEPBRIGHT"
fi
